version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: biotrace-mongo
    ports:
      - "27017:27017"
    volumes:
      - biotrace_data:/data/db
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: biotrace-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - biotrace_minio_data:/data
    restart: unless-stopped

volumes:
  biotrace_data:
  biotrace_minio_data:
